name: Test and Deploy bioimageio.core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]


jobs:
  test-no-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channel-priority: strict
        activate-environment: bio-core-dev
        environment-file: dev/environment-base.yaml
        python-version: ${{ matrix.python-version }}
    - name: pytest-base
      shell: bash -l {0}
      run: pytest


  # conda-build:
  #   runs-on: ubuntu-latest
  #   needs: test-no-deps
  #   steps:
  #   - name: checkout
  #     uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #   - name: setup conda
  #     uses: conda-incubator/setup-miniconda@v2
  #     with:
  #       auto-update-conda: true
  #       auto-activate-base: true
  #       activate-environment: ""
  #   - name: linux conda build
  #     shell: bash -l {0}
  #     run: |
  #       conda install -n base -c conda-forge conda-build pip -y
  #       conda build -c conda-forge conda-recipe
